function cf_plot_rippleactivation(dirs, params, allindex, metadata, fh, ax,  statfid, panelL, tablefilename)
%cf_plot_rippleactivation
%   plot activation and coactivation during ripples 
%ALP 3/22/2023

figure(fh)
iPlot = 1;

%% stuff for plotting
groupcolors = params.colors;
gnames = {'random', 'gamma'};
dnames = {'pre', 'post'}; 

%% load the data structure, select subset of interest
datadir = '\\ad.gatech.edu\bme\labs\singer\Abby\code\chronicflicker-ephys-prospectivecoding\results\ripples_activation_coactivation\';
load([datadir, 'ripple_activation_coactivation_placecells_RZ.mat']) %ALP 8/30/23 updated so that activation/reactivation is only RZ ripples. generated by cf_placecell_rippleactivation_RZripples
%load([datadir, 'ripple_activation_coactivation_placecells.mat'])

%% plot activation for CA1 and CA3 combined
inclData = ActivityData.nDayRipples > 10 & strcmp(ActivityData.timepoint, 'post');
PlotActivation = ActivityData(inclData,:);

nAnGamma = length(unique(PlotActivation.animal(strcmp(PlotActivation.group, 'gamma'))));
nAnRandom = length(unique(PlotActivation.animal(strcmp(PlotActivation.group, 'random'))));

disp(['There are ', num2str(nAnGamma) ' animals in 40 Hz ripple PC activation'])
disp(['There are ', num2str(nAnRandom) ' animals in Random ripple PC activation'])


axes(ax{iPlot})
hold on
vdat = []; cmat = []; stat = [];
for d = 2 %post
    datforstats = [];
    for g = 1:2
        nm = [gnames{g}, dnames{d}];
        isGroup = strcmp(PlotActivation.group, gnames{g});
        tmpdat = PlotActivation(isGroup,:).fracActive;
        vdat.(nm) = tmpdat;
        datforstats{g} = tmpdat;
        cmat = [cmat; groupcolors.(gnames{g}).(dnames{d})];
        clear tmpdat isGroup
    end
end
violinplot_half(vdat, [], 'ViolinColorMat', cmat, 'BoxWidth', 0.018, 'MedianSize', 40, 'ShowData', false);
ylabel('Activation Probability')
ylim([0 1])
    xticks([])
title(['Activation probability'])
cf_stats2txt2(datforstats, statfid, panelL{iPlot}, 'place cells', 'probability', 'activation probability', gnames, tablefilename)

clear datforstats
iPlot = iPlot+1;

%% plot coactivation for CA1-CA1 and CA3-CA3
% inclData = CoactivityData.nDayRipples > 10 & strcmp(CoactivityData.timepoint, 'post');
% PlotCoactivation = CoactivityData(inclData,:);
% 
% regNames = {'CA1CA1', 'CA3CA3'};
% 
% for r = 1:numel(regNames)
%     axes(ax{iPlot})
%     hold on
%     vdat = []; cmat = []; stat = [];
%     for d = 2 %post
%         datforstats = [];
%         for g = 1:2
%             nm = [gnames{g}, dnames{d}];
%             isGroup = strcmp(PlotCoactivation.group, gnames{g});
%             isReg = strcmp(PlotCoactivation.coactiveRegions, regNames{r});
%             tmpdat = PlotCoactivation(isGroup&isReg,:).fracCoactive;
%             vdat.(nm) = tmpdat;
%             datforstats{g} = tmpdat;
%             cmat = [cmat; groupcolors.(gnames{g}).(dnames{d})];
%             clear tmpdat isGroup
%         end
%     end
%     violinplot_half(vdat, [], 'ViolinColorMat', cmat, 'BoxWidth', 0.018, 'MedianSize', 40, 'ShowData', false);
%     ylabel('Coctivation Probability')
%     ylim([0 1])
%     xticks([])
%     title([regNames{r}])
%     cf_stats2txt2(datforstats, statfid, panelL{iPlot}, 'place cell pairs', 'probability', 'coactivation probability', gnames, tablefilename)
%     
%     clear datforstats
%     iPlot = iPlot+1;
% end

%% plot coactivation for CA1-CA1 and CA3-CA3
inclData = CoactivityData.nDayRipples > 10 & strcmp(CoactivityData.timepoint, 'post');
PlotCoactivation = CoactivityData(inclData,:);


    axes(ax{iPlot})
    hold on
    vdat = []; cmat = []; stat = [];
    for d = 2 %post
        datforstats = [];
        for g = 1:2
            nm = [gnames{g}, dnames{d}];
            isGroup = strcmp(PlotCoactivation.group, gnames{g});
            %isReg = strcmp(PlotCoactivation.coactiveRegions, regNames{r});
            tmpdat = PlotCoactivation(isGroup,:).fracCoactive;
            vdat.(nm) = tmpdat;
            datforstats{g} = tmpdat;
            cmat = [cmat; groupcolors.(gnames{g}).(dnames{d})];
            clear tmpdat isGroup
        end
    end
    violinplot_half(vdat, [], 'ViolinColorMat', cmat, 'BoxWidth', 0.018, 'MedianSize', 40, 'ShowData', false);
    ylabel('Coctivation Probability')
    ylim([0 1])
    xticks([])
    title('Coactivation')
    cf_stats2txt2(datforstats, statfid, panelL{iPlot}, 'place cell pairs', 'probability', 'coactivation probability', gnames, tablefilename)
    
    clear datforstats
    iPlot = iPlot+1;


end

